@extends('layouts.app')

@section('content')
<div class="mb-4"><a href="{{ route('admin.members.index') }}" class="btn btn-outline-secondary btn-sm"><i class="bi bi-arrow-left"></i> Back to Members</a></div>
<div class="row">
    <div class="col-lg-4 mb-4"><div class="card text-white"><div class="card-body text-center pt-4 pb-4"><div class="d-inline-flex align-items-center justify-content-center bg-dark rounded-circle mb-3" style="width: 90px; height: 90px; border: 2px solid var(--primary-blue);"><i class="bi bi-person-fill text-primary" style="font-size: 3rem;"></i></div><h4 class="fw-bold mb-1">{{ $member->nama }}</h4><p class="text-muted small mb-3">{{ $member->kode_anggota }}</p><span class="badge bg-success px-3 py-2">Active</span></div><div class="card-footer bg-dark border-0 p-4" style="border-top: 1px solid var(--border-color) !important;"><div class="mb-3"><label class="text-muted small d-block mb-1">Email</label><span class="text-white">{{ $member->email }}</span></div><div class="mb-3"><label class="text-muted small d-block mb-1">Phone</label><span class="text-white">{{ $member->telepon }}</span></div><div class="mb-3"><label class="text-muted small d-block mb-1">Address</label><span class="text-white">{{ $member->alamat }}</span></div><div class="mb-3"><label class="text-muted small d-block mb-1">Role</label><span class="badge bg-secondary">{{ ucfirst($user->role ?? $member->role) }}</span></div><div><label class="text-muted small d-block mb-1">Registered</label><span class="text-white">{{ $member->created_at->format('d F Y (H:i)') }}</span></div></div></div></div>
    <div class="col-lg-8"><div class="card text-white"><div class="card-header bg-transparent pt-4 px-4 pb-0"><h5><i class="bi bi-calendar-check text-primary me-2"></i> Room Booking History</h5></div><div class="card-body p-4">@if($roomBookings->count())<div class="table-responsive"><table class="table table-dark table-hover align-middle mb-0"><thead><tr><th>Room</th><th>Schedule</th><th>Purpose</th><th>Status</th></tr></thead><tbody>@foreach($roomBookings as $booking)<tr><td><strong>{{ $booking->room->name }}</strong><div class="small text-muted">{{ $booking->room->location }}</div></td><td class="small">{{ $booking->start_at->format('d M Y H:i') }}<br>{{ $booking->end_at->format('d M Y H:i') }}</td><td>{{ $booking->purpose }}</td><td><span class="badge {{ $booking->status === 'approved' ? 'bg-success' : ($booking->status === 'cancelled' ? 'bg-danger' : 'bg-warning text-dark') }}">{{ ucfirst($booking->status) }}</span></td></tr>@endforeach</tbody></table></div>@else<div class="py-5 text-center text-muted"><i class="bi bi-calendar-x" style="font-size: 3rem;"></i><h6 class="mt-3">No room booking history</h6><p class="mb-0 small">This member has not booked a room.</p></div>@endif</div></div></div>
</div>
@endsection
